-- Add all remaining US states to cover the full country
INSERT INTO locations (slug, type, state_code, state_name, bea_geofips, is_active)
VALUES
  ('al', 'state', 'AL', 'Alabama', 'STATE', true),
  ('ak', 'state', 'AK', 'Alaska', 'STATE', true),
  ('ar', 'state', 'AR', 'Arkansas', 'STATE', true),
  ('ct', 'state', 'CT', 'Connecticut', 'STATE', true),
  ('de', 'state', 'DE', 'Delaware', 'STATE', true),
  ('dc', 'state', 'DC', 'District of Columbia', 'STATE', true),
  ('hi', 'state', 'HI', 'Hawaii', 'STATE', true),
  ('id', 'state', 'ID', 'Idaho', 'STATE', true),
  ('in', 'state', 'IN', 'Indiana', 'STATE', true),
  ('ia', 'state', 'IA', 'Iowa', 'STATE', true),
  ('ks', 'state', 'KS', 'Kansas', 'STATE', true),
  ('ky', 'state', 'KY', 'Kentucky', 'STATE', true),
  ('la', 'state', 'LA', 'Louisiana', 'STATE', true),
  ('me', 'state', 'ME', 'Maine', 'STATE', true),
  ('md', 'state', 'MD', 'Maryland', 'STATE', true),
  ('mn', 'state', 'MN', 'Minnesota', 'STATE', true),
  ('ms', 'state', 'MS', 'Mississippi', 'STATE', true),
  ('mo', 'state', 'MO', 'Missouri', 'STATE', true),
  ('mt', 'state', 'MT', 'Montana', 'STATE', true),
  ('ne', 'state', 'NE', 'Nebraska', 'STATE', true),
  ('nv', 'state', 'NV', 'Nevada', 'STATE', true),
  ('nh', 'state', 'NH', 'New Hampshire', 'STATE', true),
  ('nj', 'state', 'NJ', 'New Jersey', 'STATE', true),
  ('nm', 'state', 'NM', 'New Mexico', 'STATE', true),
  ('nd', 'state', 'ND', 'North Dakota', 'STATE', true),
  ('ok', 'state', 'OK', 'Oklahoma', 'STATE', true),
  ('or', 'state', 'OR', 'Oregon', 'STATE', true),
  ('ri', 'state', 'RI', 'Rhode Island', 'STATE', true),
  ('sc', 'state', 'SC', 'South Carolina', 'STATE', true),
  ('sd', 'state', 'SD', 'South Dakota', 'STATE', true),
  ('tn', 'state', 'TN', 'Tennessee', 'STATE', true),
  ('ut', 'state', 'UT', 'Utah', 'STATE', true),
  ('vt', 'state', 'VT', 'Vermont', 'STATE', true),
  ('wv', 'state', 'WV', 'West Virginia', 'STATE', true),
  ('wi', 'state', 'WI', 'Wisconsin', 'STATE', true),
  ('wy', 'state', 'WY', 'Wyoming', 'STATE', true)
ON CONFLICT (slug) DO NOTHING;
